### PR TITLE
1 add submodule

### PR DESCRIPTION
**Pull request by cclarkson**

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi Chris, I think you need to add the "deps" directory to .gitignore and remove it from git, currently there are 61,767 files in this PR :-)

**Comment by alimanfoo** [comment]
Might actually be good to revert the second commit (bd4be95) then add deps to .gitignore. If you do revert you'll need to then do a force push.

**Comment by cclarkson** [comment]
Hi @alimanfoo,
Oops, should be fixed now!

**Comment by alimanfoo** [comment]
That looks better :-)

**Review by alimanfoo — APPROVED** [review]

**Comment by cclarkson** [comment]
@alimanfoo, could I have authorisation to merge please?

**Comment by alimanfoo** [comment]
Can you merge now?

**Pull request merged**
