### PR TITLE
color guides for seavobs paper

### PR DESCRIPTION
**Pull request by bstlaure**
adding notebook for color guide

### CODE REVIEW

**Comment by cclarkson** [comment]
I would recommend either generating an updated meta data csv with the group colours or start a setup.ipynb with the colours as dictionaries that can be called in future work.

**Comment by alimanfoo** [comment]
Yeah second Chris, recommend having a setup.ipynb which has dictionaries mapping groups or species to colours, rather than bake colours into a sample metadata file. Then if you ever want to change the colours in future (heaven forbid :-) you only have to change them in one place.

**Comment by bstlaure** [comment]
Have started a setup notebook and added csv files with colors associated with each species, species group, and alignment in a folder "meta"

**Comment by cclarkson** [comment]
Hi @bstlaure,

For the Ag1000g setup.ipynb we have included all the info in the notebook rather than as separate files which get loaded in. 

With a normal notebook you would not do this, but the idea behind the setup notebook is to produce a single file which sits behind all your other notebooks and has all the ugly/large/boring bits of regularly referred-to code inside. 

A good way to do this is to make dictionaries of these data in the setup notebook itself.

**Pull request closed without merging**
